apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-nginx
  name: gitops-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: 192.168.1.10:8443/echo-ip 
